services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "DFSGNJDIO84WRESGNJS!1"
    ports:
      - "1433:1433"